name: Copy Folders to Directory

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the `main` branch

jobs:
  copy-folders:
    runs-on: self-hosted  # Use a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy Folders
        run: |
          cp -R *.* /web

